[tool.poetry]
name = "ai-development"
version = "1.0.0"
description = "KI Professional – Fachrichtung Development"
authors = ["Daniel Senften <daniel.senften@talent-factory.ch>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
tensorflow = "^2.18.0"
sentence-transformers = "^3.2.1"
streamlit = "^1.40.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
