[tool.poetry]
name = "ai-development"
version = "1.0.0"
description = "KI Professional – Fachrichtung Development"
authors = ["Daniel Senften <daniel.senften@talent-factory.ch>"]
license = "MIT"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
tensorflow = "^2.15.0"
sentence-transformers = "^3.2.1"
streamlit = "^1.40.0"
langchain = "^0.3.19"
langchain_openai = "^0.3.7"
langchain_community = "^0.3.18"
openai = "^1.64.0"
faiss-cpu = "^1.10.0"
pypdf2 = "^3.0.1"
chromadb = "^0.6.1"
tiktoken = "^0.9.0"
python-dotenv = "^1.0.1"
numpy = "~1.26.4"
transformers = "^4.49.0"
replicate = "^1.0.4"
pypdf = "^5.5.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
